#lane_control/lane_controller_node
#v_bar_old 0.45
v_bar: 0.45
# k_d_old: -12
k_d: -12      #-10.30
# k_theta_old: -6.0
k_theta: -6.0       #-9.0 #-5.15
theta_thres: 0.523    #0.523
d_thres: 0.2615        #0.2615
d_offset: -0.0      #0.0

